### ISSUE TITLE
Fail to run blip2_image_text_matching.ipynb in Colab at model() fucntion

### ISSUE THREAD

**Issue by dragonwhl** [salesforce/LAVIS#119]
I test blip2_image_text_matching.ipynb which in directory "LAVIS/examples",
when run at:
itm_output = model({"image": img, "text_input": txt}, match_head="itm")
itm_scores = torch.nn.functional.softmax(itm_output, dim=1)
print(f'The image and text are matched with a probability of {itm_scores[:, 1].item():.3%}')

got error like this:
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-8-24991d5587c1>] in <module>
----> 1 itm_output = model({"image": img, "text_input": txt}, match_head="itm")
      2 itm_scores = torch.nn.functional.softmax(itm_output, dim=1)
      3 print(f'The image and text are matched with a probability of {itm_scores[:, 1].item():.3%}')

9 frames
[/usr/local/lib/python3.8/dist-packages/torch/nn/modules/conv.py](https://localhost:8080/#) in _conv_forward(self, input, weight, bias)
    457                             weight, bias, self.stride,
    458                             _pair(0), self.dilation, self.groups)
--> 459         return F.conv2d(input, weight, bias, self.stride,
    460                         self.padding, self.dilation, self.groups)
    461 

RuntimeError: Input type (float) and bias type (c10::Half) should be the same

**Comment by dxli94** [comment]
This is a bug. In the previous version, we did not enable autocast for ViT. This should be fixed now.

**Comment by youngkyunJang** [comment]
Hello, thanks for your wonderful and quick response! I had a same issue for Feature Extraction Example, 
and I add

'with torch.cuda.amp.autocast(enabled=(device != torch.device("cpu"))):'

on top of it as you did in https://github.com/salesforce/LAVIS/commit/b345799749811fc06156a99f877be01b7a91bf56 ,
and it worked. To let others know :)

**Comment by piterand** [comment]
`examples/blip2_feature_extraction.ipynb` does not work because the same error `Input type (float) and bias type (c10::Half) should be the same`

**Comment by dxli94** [comment]
@piterand are these issues still impacting the current version?

I tested on https://github.com/salesforce/LAVIS/commit/3b8df58666e47437999e1cbcc72262e54af5d9e8 and it seems to work fine.

**Comment by piterand** [comment]
Thank you. @dxli94 for your answer. 
Now the code is working for the GPU without `with torch.cuda.amp.autocast(enabled=(device != torch.device("cpu"))):`
But it still not working for the CPU. It gives the error: `Input type (float) and bias type (c10::Half) should be the same`

**Comment by dxli94** [comment]
@piterand, with https://github.com/salesforce/LAVIS/commit/baad2d7c8df599d8d9b081ba2e946626eaa2dc34 it should work on CPU, too.

Thanks for the feedback.
